apiVersion: snapshot.kubevirt.io/v1beta1
kind: VirtualMachineSnapshot
metadata:
  name: "{{ .name }}-{{ .counter }}-{{ .Replica }}"
spec:
  deletionPolicy: delete
  source:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: "{{ .name }}-{{ .counter }}-{{ .Replica }}"
